get_lyric_form:
    path:     /getLyric
    defaults: { _controller: EditLyricsBundle:Default:getLyric }
    methods:  POST
    
save_lyricsWord_form:
    path:     /saveLyricsWord
    defaults: { _controller: EditLyricsBundle:Default:saveLyricsWord }
    methods:  POST
    
delete_lyricsWord_form:
    path:     /deleteLyricsWord
    defaults: { _controller: EditLyricsBundle:Default:deleteLyricsWord }
    methods:  POST